//--------------------------------------//
// Importing the necessary dependencies //
//--------------------------------------//
import './App.css';
import { BrowserRouter as Router, Route, Routes, Link } from 'react-router-dom';
import Login from './pages/Login';
import NewPost from './pages/NewPost';
import Post from './pages/Post';
import Posts from './pages/Posts';
import Register from './pages/Register';
import Logo from './images/icon-left-font-monochrome-white.png';
//-----------------------------------------------------------//
// An empty App function is automatically generated by REACT //
//-----------------------------------------------------------//
function App() {
  //---------------------------//
  // Return the HTML to inject //
  //---------------------------//
  return (
    <div className="App">
      <Router>
        <div className="navbar">
          <img className="logo" src={Logo} alt="Logo" />
          <Link to="/">Se connecter</Link>
          <Link to="/register">Créer un compte</Link>
          <Link to="/newpost">Créer un message</Link>
          <Link to="/posts">Voir les messages</Link>
        </div>
        <Routes>
          <Route path="/" exact element={<Login />} />
          <Route path="/register" exact element={<Register />} />
          <Route path="/posts" exact element={<Posts />} />
          <Route path="/post/:id" exact element={<Post />} />
          <Route path="/newpost" exact element={<NewPost />} />
        </Routes>
      </Router>
    </div>
  );
}
//-------------------------//
// export the App function //
//-------------------------//
export default App;
